# Matrix Multiplication

In [2]:
a = [[1,3, 2,3],[4,3,5,6],[7,8,9,3],[1,2,3,4]]
b = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]

def Multiplication(a,b):
    """
    Matrix Multiplication
    """
    if len(a) ==len(b):
        result_list = []
        result_matrix = []

        for i in range(len(a)):
            for j in range(len(b)):
                add = 0
                for k in range(len(a)):
                    add = add + a[i][k] * b[k][j]
                result_list.append(add)
        for k in range(0, len(a)*len(b), len(a)):
            result_matrix.append(result_list[k:k+len(a)])
        return result_matrix
    else:
        return("Matrix multiplication is not possible [Not same Dimentions]")
Multiplication(a,b)


[[1, 3, 2, 3], [4, 3, 5, 6], [7, 8, 9, 3], [1, 2, 3, 4]]

In [3]:
import numpy as np
print(np.dot(a,b))

[[1 3 2 3]
 [4 3 5 6]
 [7 8 9 3]
 [1 2 3 4]]


# Replace numbers with "#"

In [7]:
import re

#INPUT'S
A = "234" 
B = "a2b3c4" 
C = "abc" 
D = "#2a$#b%c%561#"

def replace(s):
    """
    Replace numbers with #
    """
    if type(s) == str:
        s = re.sub("[^0-9]","",str(s))
        s =re.sub("\d","#", s)
        print(s)
    else:
        return "Please Enter valid string"
    
replace(A)
replace(B)
replace(C)
replace(D)

###
###

####


# Print name of students

In [8]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def get_student(Students,Marks):
    """
    print Who got top 5 ranks, Who got least 5 ranks and Who got marks in IQR 
    """
    dic = dict(zip(Students,Marks))

    print("Who got top 5 ranks")
    first_five = (sorted(dic.values())[5:])[::-1]
    for m in first_five:
        print("Name :", list(dic.keys())[list(dic.values()).index(m)])
        print("Marks:", m)
    
    print("\n")
    
    print("Who got least 5 ranks")
    last_five = (sorted(dic.values())[:5])
    for m in last_five:
        print("Name :", list(dic.keys())[list(dic.values()).index(m)])
        print("Marks ", m )
    
    print("\n")
    
    print("Who got marks in IQR")
    for m in dic.values():
        if ( m >= 25 and m <= 75 ):
            print("Name :", list(dic.keys())[list(dic.values()).index(m)])
            print("Marks :", m)
            
        else:
            pass
        

get_student(Students,Marks)

Who got top 5 ranks
Name : student8
Marks: 98
Name : student10
Marks: 80
Name : student2
Marks: 78
Name : student5
Marks: 48
Name : student7
Marks: 47


Who got least 5 ranks
Name : student3
Marks  12
Name : student4
Marks  14
Name : student9
Marks  35
Name : student6
Marks  43
Name : student1
Marks  45


Who got marks in IQR
Name : student1
Marks : 45
Name : student5
Marks : 48
Name : student6
Marks : 43
Name : student7
Marks : 47
Name : student9
Marks : 35


In [ ]:
# 

In [9]:
import math

P = (3,4)
S = [(2,-1), (5,3),(4,-1),(2,1),(2,-3),(-1,2),(-3,4),(-4,2)]
distance = {}

def close_points(point,point_list):
    for i in range(len(point_list)):
        d = math.acos(((point_list[i][0]*point[0])+(point_list[i][1]*point[1]))/((math.sqrt((point_list[i][0]**2)+(point_list[i][1]**2))) *(math.sqrt((point[0]**2)+(point[1]**2)))))
        distance[point_list[i]] = d

    dis = sorted(distance.values())[:5]

    print("Closes point from P :")
    for m in dis:
        print("Distance from P(3,4) point to the {}".format(list(distance.keys())[list(distance.values()).index(m)]))        
    
                        
close_points(P, S)

Closes point from P :
Distance from P(3,4) point to the (5, 3)
Distance from P(3,4) point to the (2, 1)
Distance from P(3,4) point to the (-1, 2)
Distance from P(3,4) point to the (4, -1)
Distance from P(3,4) point to the (-3, 4)


In [3]:
import re

green =[(5,2),(2,1),(2,5)]
red  =[(-2,-3),(-1,-4)]
lines =["1x+1y+0","1x-1y+0","1x+0y-4","0x-1y-2"]


def clf_classes(a,b,c):
    g = []
    rd= []
    for i in range(len(green)):
        r = ((a*green[i][0])+(b*green[i][1])+c)
        g.append(r)

    for i in range(len(red)):
        s = ((a*red[i][0])+(b*red[i][1])+c)
        rd.append(s)

    finalrd = all(j > 0 for j in rd)
    finalgr = all(j < 0 for j in g)

    if (finalgr == True and finalrd == True):
        print("classified using line {}x+{}y+{}".format(a,b,c))
    else:
        print("Not classified " )

for line in lines:
    a, b, c = [int(x.strip()) for x in re.split('x|y', line)]
    clf_classes(a,b,c)


Not classified 
Not classified 
Not classified 
classified using line 0x+-1y+-2
